language: node_js
node_js:
    - node
    - 10.13.0
cache: npm

script: npm run lint && npm test

after_success:
    - codecov && cat ./coverage/lcof.info | ./node_modules/.bin/coveralls

notifications:
    - emails: false
