language: node_js
node_js:
    - node
    - 10

cache: npm

script: npm run lint && npm test

after_success:
    - codecov && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

notifications:
    - emails: false
